const mottos = [
    "Just do it", "Stay hungry, stay foolish", "Believe in yourself", "Never give up", "Carpe Diem",
    "Dream big", "Work hard, stay humble", "Be kind always", "Stay positive", "Keep moving forward",
    "Focus on the good", "Make it happen", "Be your own hero", "Choose joy", "Live in the moment",
    "Follow your heart", "Stay strong", "Be the change", "Do what you love", "Love what you do",
    "Don't stop until you're proud", "Everything happens for a reason", "Good things take time", "Progress over perfection", "You are enough",
    "Start where you are", "Use what you have", "Do what you can", "Breathe in, breathe out", "Happiness is a choice",
    "Keep it simple", "Learn something new every day", "Success is a journey", "Take the risk", "Trust the process",
    "Wake up and be awesome", "Your only limit is you", "Action is the key", "Always be learning", "Aspire to inspire",
    "Be a voice, not an echo", "Be bold, be brave", "Be fearless", "Better late than never", "Challenge yourself",
    "Collect moments, not things", "Commit to your goals", "Confidence is key", "Create your own sunshine", "Creativity takes courage",
    "Determination leads to success", "Do more of what makes you happy", "Don't dream it, be it", "Don't quit your day dream", "Dream it. Wish it. Do it.",
    "Effort is everything", "Enjoy the little things", "Every day is a second chance", "Explore the unexplored", "Fail forward",
    "Find your fire", "Focus on your potential", "Get it done", "Go for it", "Go the extra mile",
    "Gratitude changes everything", "Grow through what you go through", "Hard work pays off", "Have faith in your dreams", "Hold the vision, trust the process",
    "Hustle and heart will set you apart", "I can and I will", "Imagine the possibilities", "Inhale courage, exhale fear", "Innovation is the way",
    "Inspire others", "It's a beautiful day", "Keep going, keep growing", "Kindness is free", "Let your light shine",
    "Life is a journey", "Listen to your soul", "Live a life you love", "Live, laugh, love", "Look for the magic in every day",
    "Love yourself first", "Make today count", "Mindset is everything", "Never look back", "No guts, no glory",
    "Nothing is impossible", "One day at a time", "Opportunity is everywhere", "Passion is power", "Patience is a virtue",
    "Persistence prevails", "Play hard, work harder", "Practice makes perfect", "Purpose drives us", "Quality over quantity",
    "Reach for the stars", "Remember why you started", "Respect the journey", "Rise and grind", "Seek adventure",
    "Self-love is the best love", "She turned her can'ts into cans", "Shoot for the moon", "Show up and shine", "Small steps, big results",
    "Stay curious", "Stay dedicated", "Stay focused", "Stay humble", "Stay inspired",
    "Stay wild", "Strive for greatness", "Take it easy", "The best is yet to come", "The future is bright",
    "The sky is the limit", "The time is now", "Think outside the box", "Today is a gift", "Together we can",
    "Turn your dreams into reality", "Unleash your potential", "Victory is sweet", "Vision is the art of seeing the invisible", "Wait for nothing",
    "Way of the warrior", "We are the champions", "Whatever it takes", "Win from within", "Work hard, play hard",
    "Yes you can", "You can do anything", "You got this", "You only live once", "Your life, your choice",
    "Abundance is a mindset", "Adventure awaits", "All is well", "Always keep fighting", "Amplify your impact",
    "Art is everywhere", "Be a light", "Be authentic", "Be grateful", "Be present",
    "Begin again", "Beyond limits", "Build your empire", "Call to action", "Celebrate every win",
    "Change is good", "Chase excellence", "Choose kindness", "Climb the mountain", "Dare to dream",
    "Design your life", "Diligence is the mother of good luck", "Discipline equals freedom", "Do it with passion", "Dream beyond borders",
    "Elevate your game", "Embrace the journey", "Empower yourself", "Endless possibilities", "Energy flows where intention goes",
    "Enjoy the ride", "Excel in all you do", "Expand your horizons", "Expect greatness", "Explore your world",
    "Fearless heart", "Feel the rhythm", "Find your balance", "Find your flow", "Find your peace",
    "Focus on what matters", "For the win", "Forgive and forget", "Fortune favors the bold", "Fuel your fire",
    "Full steam ahead", "Get after it", "Give it your all", "Go big or go home", "Go get 'em",
    "Gold in every moment", "Good vibes only", "Grace under pressure", "Great things are coming", "Grit and grace",
    "Happiness looks good on you", "Harmony in life", "Head held high", "Heart of a lion", "Heighten your senses",
    "Honesty is the best policy", "Hope is a waking dream", "Humble and hungry", "I am the captain of my soul", "Ignite your passion",
    "Impact over intention", "Inner strength", "Inspiring greatness", "Into the blue", "Invest in yourself",
    "It's all good", "Journey to the top", "Just breathe", "Keep the faith", "Lead by example",
    "Lead from the heart", "Learn and grow", "Legacy in the making", "Let it be", "Level up",
    "Life is what you make it", "Limitless potential", "Live bold", "Live with purpose", "Love unconditionally",
    "Make magic happen", "Make your mark", "Master your mind", "Mindfulness matters", "Mission possible",
    "Momentum is key", "Never settle", "No excuses", "Nothing can stop you", "One life, one chance",
    "Own your story", "Pave your own path", "Peace of mind", "Persistence is powerful", "Positive vibes only",
    "Power through", "Pure intentions", "Push your boundaries", "Quality of life", "Quiet confidence",
    "Radiate positivity", "Raise the bar", "Realize your dreams", "Refine your craft", "Relentless pursuit",
    "Resilience is beautiful", "Respect the hustle", "Rise above", "See the beauty", "Seek the truth",
    "Set the trend", "Simplify your life", "Sparkle every day", "Speak your truth", "Stay authentic"
];
